// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUQjXSt1fl7GtfDx9FA3KSwHtzTiWMcY',
    appId: '1:947361107260:web:26b19b006ca8d67ee2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    authDomain: 'gearup-ceeb0.firebaseapp.com',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
    measurementId: 'G-0Y69D812DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAJbWqy94oiFZNmOn6oLIqNd4ORAkj3Y',
    appId: '1:947361107260:android:55c50d669c8882d9e2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIFBl0QXQSLQ3nC55X00_eNp4oZbcRYw',
    appId: '1:947361107260:ios:1866ca8c1e051aa8e2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
    iosBundleId: 'com.gearup.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaIFBl0QXQSLQ3nC55X00_eNp4oZbcRYw',
    appId: '1:947361107260:ios:1866ca8c1e051aa8e2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
    iosBundleId: 'com.gearup.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNUQjXSt1fl7GtfDx9FA3KSwHtzTiWMcY',
    appId: '1:947361107260:web:6750454538b94830e2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    authDomain: 'gearup-ceeb0.firebaseapp.com',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
    measurementId: 'G-69N8YLPTJB',
  );
}
