// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAJbWqy94oiFZNmOn6oLIqNd4ORAkj3Y',
    appId: '1:947361107260:android:d96311d73e344e03e2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIFBl0QXQSLQ3nC55X00_eNp4oZbcRYw',
    appId: '1:947361107260:ios:7ec18ae14bac0a0de2a239',
    messagingSenderId: '947361107260',
    projectId: 'gearup-ceeb0',
    storageBucket: 'gearup-ceeb0.firebasestorage.app',
    androidClientId: '947361107260-bij2k79laobhpgg3rfeg8itsa99hv78j.apps.googleusercontent.com',
    iosClientId: '947361107260-ava4aoun4v5mvepdtshqk1n27jlvuu7t.apps.googleusercontent.com',
    iosBundleId: 'com.gearup.app',
  );
}
