name: iOS Build Only (no signing)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: "stable"
          architecture: "arm64"
      - name: Pub get
        run: flutter pub get
      - name: Pods install
        working-directory: ios
        run: |
          rm -f Podfile.lock
          pod install --repo-update
      - name: Archive (no signing)
        run: |
          flutter clean
          flutter build ios --release --no-codesign
      - name: Upload xcode build logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcode-logs
          path: ~/Library/Logs/DiagnosticReports/*
          if-no-files-found: ignore