name: ios

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-14

    env:
      APP_BUNDLE_ID: com.gearup.app
      KEYCHAIN_NAME: signing_${{ github.run_id }} # unique per run

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: flutter-stable-3.35.5-arm64

      - name: Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.5'
          architecture: arm64

      - name: Precache iOS engine & write podhelper/xcconfig
        shell: bash
        run: |
          set -euo pipefail
          flutter precache --ios --no-universal --force

          FLUTTER_BIN="$(which flutter)"
          FLUTTER_ROOT="$(cd "$(dirname "$FLUTTER_BIN")/.." && pwd -P)"
          echo "FLUTTER_ROOT=$FLUTTER_ROOT" >> "$GITHUB_ENV"

          mkdir -p ios/Flutter
          cp "$FLUTTER_ROOT/packages/flutter_tools/bin/podhelper.rb" ios/Flutter/podhelper.rb

          cat > ios/Flutter/Generated.xcconfig <<EOF
          FLUTTER_ROOT=$FLUTTER_ROOT
          FLUTTER_APPLICATION_PATH=$GITHUB_WORKSPACE
          FLUTTER_TARGET=lib/main.dart
          DART_OBFUSCATION=false
          TRACK_WIDGET_CREATION=false
          TREE_SHAKE_ICONS=true
          PACKAGE_CONFIG=.dart_tool/package_config.json
          EOF

      - name: flutter pub get
        run: flutter pub get

      - name: CocoaPods install
        shell: bash
        run: |
          set -euo pipefail
          pushd ios
          pod repo update
          # If you had a previous lock with wrong settings, clear it:
          rm -f Podfile.lock
          pod install
          popd

      # ✅ Import certs ONCE with a unique keychain name
      - name: Import code signing cert
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_CERT_P12_PASSWORD }}
          keychain: ${{ env.KEYCHAIN_NAME }}
          create-keychain: true

      # (Optional) Download provisioning profile(s) if you use manual profiles
      # - name: Download provisioning profiles
      #   uses: apple-actions/download-provisioning-profiles@v1
      #   with:
      #     bundle-id: ${{ env.APP_BUNDLE_ID }}
      #     issuer-id: ${{ secrets.ASC_ISSUER_ID }}
      #     api-key-id: ${{ secrets.ASC_KEY_ID }}
      #     api-private-key: ${{ secrets.ASC_KEY_P8_BASE64 }}

      - name: Build IPA (App Store)
        shell: bash
        run: |
          set -euo pipefail
          INCLUDE_LINE='#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"'
          FILE="ios/Flutter/Release.xcconfig"
          grep -Fq "$INCLUDE_LINE" "$FILE" || echo "$INCLUDE_LINE" >> "$FILE"

          flutter build ipa --release --export-options-plist=ios/ci_export_appstore.plist

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/*.ipa
          issuer-id: ${{ secrets.ASC_ISSUER_ID }}
          api-key-id: ${{ secrets.ASC_KEY_ID }}
          api-private-key: ${{ secrets.ASC_KEY_P8_BASE64 }}