name: iOS Build & Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-15

    env:
      APP_BUNDLE_ID: com.gearup.app
      TEAM_ID: M282YL56RT
      PROFILE_NAME: GearupAppStore
      KEYCHAIN_NAME: signing_${{ github.run_id }}
      FLUTTER_VERSION: 3.35.5
      XCODE_VERSION: 16.1

    steps:
      # -------------------------------------------------------
      # 1️⃣ Checkout and setup environment
      # -------------------------------------------------------
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'     # ⬅️ instead of 16.1

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          architecture: arm64

      # -------------------------------------------------------
      # 2️⃣ Prepare Flutter build
      # -------------------------------------------------------
      - name: 🔧 Precache Flutter iOS artifacts
        run: |
          flutter precache --ios --no-universal --force

      - name: 🧹 Clean and get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: 🍫 Install CocoaPods
        working-directory: ios
        run: |
          pod repo update
          pod install --verbose

      # -------------------------------------------------------
      # 3️⃣ Import certificates and profiles
      # -------------------------------------------------------
      - name: 🔐 Import signing certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERT_P12_BASE64 }}
          p12-password:    ${{ secrets.IOS_CERT_P12_PASSWORD }}
          keychain:        ${{ env.KEYCHAIN_NAME }}
          create-keychain: true

      - name: 🗝️ Make keychain default
        run: security default-keychain -s "${KEYCHAIN_NAME}.keychain"

      - name: 📲 Download provisioning profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id:        ${{ env.APP_BUNDLE_ID }}
          issuer-id:        ${{ secrets.ASC_ISSUER_ID }}
          api-key-id:       ${{ secrets.ASC_KEY_ID }}
          api-private-key:  ${{ secrets.ASC_KEY_P8 }}
          profile-type:     IOS_APP_STORE

      - name: 🧩 Ensure iOS platform installed
        run: |
          sudo xcodebuild -downloadPlatform iOS

      # -------------------------------------------------------
      # 4️⃣ Build archive for App Store
      # -------------------------------------------------------
      - name: 🏗️ Build signed iOS IPA with Flutter
        run: |
          set -euo pipefail
          echo "🏗️ Building and signing iOS IPA via Flutter..."

          flutter build ipa \
            --release \
            --export-options-plist=ios/ci_export_appstore.plist \
            --build-number=${{ github.run_number }} \
            --no-tree-shake-icons

          echo "✅ Flutter build complete"

      # -------------------------------------------------------
      # 5️⃣ Export IPA
      # -------------------------------------------------------
      - name: 📦 Export IPA for App Store
        run: |
          set -euo pipefail
          mkdir -p build/export
          cp ios/ci_export_appstore.plist build/ci_export_appstore.plist
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist build/ci_export_appstore.plist \
            -exportPath build/export
          echo "✅ IPA exported to build/export/Runner.ipa"

      # -------------------------------------------------------
      # 6️⃣ Upload to TestFlight
      # -------------------------------------------------------
      - name: ☁️ Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/Runner.ipa
          issuer-id: ${{ secrets.ASC_ISSUER_ID }}
          api-key-id: ${{ secrets.ASC_KEY_ID }}
          api-private-key: ${{ secrets.ASC_KEY_P8 }}

      # -------------------------------------------------------
      # 7️⃣ Upload artifacts for debugging
      # -------------------------------------------------------
      - name: 🧾 Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: |
            build/Runner.xcarchive
            build/export
